// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdggO6SDCZ-qFNcOAm0NYO5Z_VFH5-P1U',
    appId: '1:419525976305:web:4bc839343136f09cccc950',
    messagingSenderId: '419525976305',
    projectId: 'async-test-497e8',
    authDomain: 'async-test-497e8.firebaseapp.com',
    storageBucket: 'async-test-497e8.appspot.com',
    measurementId: 'G-5J6KGL96R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3WPA-W62zxgBTblxseDOBaHV8W3fDK4',
    appId: '1:419525976305:android:56669c151f622fe0ccc950',
    messagingSenderId: '419525976305',
    projectId: 'async-test-497e8',
    storageBucket: 'async-test-497e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Txe2E690XraTjQv0Zsie5vvrBA2Xnk0',
    appId: '1:419525976305:ios:d3cb053077d26c24ccc950',
    messagingSenderId: '419525976305',
    projectId: 'async-test-497e8',
    storageBucket: 'async-test-497e8.appspot.com',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Txe2E690XraTjQv0Zsie5vvrBA2Xnk0',
    appId: '1:419525976305:ios:d3cb053077d26c24ccc950',
    messagingSenderId: '419525976305',
    projectId: 'async-test-497e8',
    storageBucket: 'async-test-497e8.appspot.com',
    iosBundleId: 'com.example.tms',
  );
}
